name: 'Hello World'
description: 'Greet someone'
inputs:
  bucketName:  # id of input
    description: 'Bucket to empty'
    required: true
runs:
  using: "composite"
  steps:
    - name: Inline python step
      env: 
        BUCKET_NAME: 
      run: |
        import boto3
        s3 = boto3.resource('s3')
        bucket = s3.Bucket(os.environ['BUCKET_NAME'])
        bucket.object_versions.delete()
      shell: python